# -*- encoding: utf-8 -*-
require 'java'
require 'rake/javaextensiontask'

Rake::JavaExtensionTask.new('nn') do |ext|
  ext.name = 'nn'
  ext.debug = true
  ext.lib_dir = 'library/nn'
  ext.source_version = '1.7'
  ext.target_version = '1.7'
end
