desc 'Default'
task :default => [:compile, :install, :run]

desc 'Compile'
task :compile do
  sh 'mvn package'
end

desc 'Move xor jar'
task :install do
  sh 'mkdir -p library/xor' unless File.exist?('./library/xor')
  sh 'mv target/xor-1.0-SNAPSHOT.jar library/xor/xor.jar'
end

desc 'Run'
task :run do
  exec 'k9 -r xor.rb'
end
